---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
    -
      name: mysql
      port: 3306
      protocol: TCP
  selector:
    app: laravel-mysql
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        -
          env:
            -
              name: MYSQL_ROOT_PASSWORD
              value: root_password
            -
              name: MYSQL_DATABASE
              value: laravel-database
          image: "mysql:5.7"
          name: cont-laravel-mysql
          ports:
            -
              containerPort: 3306
              name: mysql
              protocol: TCP
          volumeMounts:
            -
              mountPath: /var/lib/mysql
              name: vol-laravel
              subPath: dbdata
      volumes:
        -
          name: vol-laravel
          persistentVolumeClaim:
            claimName: laravel-pvc-mysql
